// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/contact.tsx";
import * as $2 from "./routes/projects.tsx";
import * as $$0 from "./islands/Disqus.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/contact.tsx": $1,
    "./routes/projects.tsx": $2,
  },
  islands: {
    "./islands/Disqus.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
