// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/blog/[slug].tsx";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/gfm.css.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/projects.tsx";
import * as $$0 from "./islands/Disqus.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/about.tsx": $2,
    "./routes/blog/[slug].tsx": $3,
    "./routes/contact.tsx": $4,
    "./routes/gfm.css.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/projects.tsx": $7,
  },
  islands: {
    "./islands/Disqus.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
